######################################################################
# Automatically generated by qmake (2.01a) dim. dec. 23 13:48:52 2007
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS = src
