######################################################################
# Automatically generated by qmake (2.01a) dim. déc. 23 13:49:28 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT = core

# Input
SOURCES += ruleparser.cpp
